- name: Create a directory if it does not exist
  file:
    path: /etc/certs/{{ domain }}
    state: directory
    mode: '0755'

- name: Transfer cert+key
  synchronize:
    src: data/live/{{ domain }}/
    dest: /etc/certs/{{ domain }}
    copy_links: yes
    delete: yes

- name: Server restart
  shell: service {{ server }} reload
  when: ("{{ server }}" != "gitlab")

- name: Gitlab restart
  shell: gitlab-ctl restart nginx
  when: ("{{ server }}" == "gitlab")
