- name: Create a directory if it does not exist
  file:
    path: /etc/certs/{{ item }}
    state: directory
    mode: '0755'
  with_items: "{{ group_names }}"

- name: Transfer cert+key
  synchronize:
    src: data/live/{{ item }}/
    dest: /etc/certs/{{ item }}
    copy_links: yes
    delete: yes
  with_items: "{{ group_names }}"

- name: Server restart
  shell: service {{ server }} reload
  when: ("{{ server }}" != "gitlab")

- name: Gitlab restart
  shell: gitlab-ctl restart nginx
  when: ("{{ server }}" == "gitlab")
